# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage : GenerateArtefact
  jobs:
    - job: Artefact
      steps:
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
        
      
- stage : InfrastructureDeployment
  pool:
   vmImage: 'ubuntu-latest' 
  jobs: 
  - job: Infrasturcture
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'artifact01'
        targetPath: '$(Build.ArtifactStagingDirectory)'
    

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'Free Trial(85e6bef8-2ce5-4936-b26a-102ce2668487)'
          subscriptionId: '85e6bef8-2ce5-4936-b26a-102ce2668487'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'madhur-rg'
          location: 'Central US'
          templateLocation: 'Linked artifact'
          csmFile: '$(Build.ArtifactStagingDirectory)/artifact01/armtemplate/ACRAKS.json'
          csmParametersFile: '$(Build.ArtifactStagingDirectory)/artifact01/armtemplate/ACRAKSParameter.json'
          deploymentMode: 'Incremental'

    

