# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage : Generate Artefact
  jobs:
    - job: Artefact
      steps:
        - publish: $(System.DefaultWorkingDirectory)
          artifact : code
      
# - stage : Infrastructure Deployment
#   pool:
#    vmImage: 'ubuntu-latest' 
#   jobs: 
#   - job: Infrasturcture
#     steps:
#       - 

    

